### ISSUE TITLE
the input to pagerank_power

### ISSUE THREAD

**Issue by bakerhassan** [asajadi/fast-pagerank#2]
What did you mean by saying the input `A is a graph`? Is it the adjacency matrix? Laplacian matrix? Google matrix or stochastic matrix? Can you please provide the mathematical formula in terms of one of the aforementioned matrices? I know that in order to a pagerank converge, the input matrix must be a positive matrix.

**Comment by asajadi** [comment]
Sorry, but I can't remember where I've said that. I've tried to emphasize that it's always a sparse adjacency matrix, in the CSR format.
