### ISSUE TITLE
"Start with x = e/n"

### ISSUE THREAD

**Issue by DavidNemeskey** [asajadi/fast-pagerank#3]
Hi,

I might have noticed a slight error in the implementation of the power method.

I use the power method to compute the PR in my program, and it seemed to be a bit slow. I had a look at Moler's algorithm, and it says

_Start with_
```
x = e / n
```
So I made the change (`x = s / n`) on [line 106](https://github.com/asajadi/fast-pagerank/blob/792c4bc8760032a6ababc9553f229ff702d300f5/fast_pagerank/fast_pagerank.py#L106) and it seems to have sped convergence up somewhat. Would you check it as well to see if it is indeed an error and if the speed-up is systematic and not anecdotal?

**Comment by asajadi** [comment]
Hey @DavidNemeskey,
My bad for the late response! Just checked this out. Yeah, you've got a point there. Thanks for spotting it! I'll fix it.
